name: power_diyala
description: "A full-power aio team helper"
publish_to: 'none'
version: 0.25.05+8

environment:
  sdk: ^3.5.3

# ---------------------- PACKAGES ---------------------#
dependencies:
  flutter:
    sdk: flutter

   # Icons
  cupertino_icons: ^1.0.8
  simple_icons: ^14.6.1

   # Internet
  http: ^1.2.2
  connectivity_plus: ^6.1.2

   # Secrets
  flutter_dotenv: ^5.1.0

   # Navigation
  go_router: ^16.0.0

   # Local Storage
  shared_preferences: ^2.5.2
  sqflite_sqlcipher: ^3.1.0+1

   # State Management
  provider: ^6.1.2

   # Pickers
  file_picker: ^10.1.2
  flutter_colorpicker: ^1.1.0
  flutter_datetime_picker_plus: ^2.2.0
  image_picker: ^1.1.2

   # Firebase & Supabase
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  firebase_core: ^4.0.0
  firebase_remote_config: ^6.0.0

   # Device Related
  permission_handler: ^12.0.0+1
  device_info_plus: ^11.3.0

   # Notification Related
  flutter_local_notifications: ^19.1.0
  timezone: ^0.10.0

   # Core Packages
  path_provider: ^2.1.4
  path: ^1.9.0
  intl: ^0.20.1
  url_launcher: ^6.3.0

   # Logging
  logger: ^2.4.0
  fluttertoast: ^8.2.8

   # Utility
  flutter_native_splash: ^2.4.2
  flutter_email_sender: ^7.0.0
  flutter_speed_dial: ^7.0.0
  table_calendar: ^3.2.0
  fl_chart: ^1.0.0
  animated_bottom_navigation_bar: ^1.3.3
  auto_size_text: ^3.0.0
  marquee: ^2.3.0
  lottie: ^3.1.3
  maps_launcher: ^3.0.0+1
  restart_app: ^1.3.2


# ---------------------- END OF PACKAGES ---------------------#
dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0



flutter:
  uses-material-design: true

# ---------------------- ASSETS ---------------------#

  assets:
  - assets/the_data.db
  - assets/
  -  .env
  - assets/powerdiyala.json



