class CMMapper {
  final Map<String, Map<String, dynamic>> sheetMappings = {
    'Generator': {
      'templateFileId': '165kXvZcOPkYG6d9-5kdeGMTBDzNZjtyPrN1S9SINdmc',
      'sheetName': 'Gen',
      'cells': {
        'C3': 'location',
        'G3': 'siteName',
        'J3': 'siteCode',
        'I2': 'date',
        'C4': 'cmType',
        'H4': 'cmCategory',
        'K4': 'extraType',
        'D6': 'time',
        'F7': 'tech name',
        'F8': 'escalated',
        'F9': 'engineer name',
        'H6': 'G1',
        'H7': 'G2',
        'H9': 'CP',
        'J9': 'Kwh',
        'J6': 'T1',
        'J7': 'T2',
        'J8': 'T3',
        'A14': 'Comments1',
        'G14': 'Comments2',
        'A16': 'item1Code',
        'H16': 'item1Quantity',
        'K16': 'item1UsedFor',
        'L16': 'item1Where',
        'A17': 'item2Code',
        'H17': 'item2Quantity',
        'K17': 'item2UsedFor',
        'L17': 'item2Where',
        'A18': 'item3Code',
        'H18': 'item3Quantity',
        'K18': 'item3UsedFor',
        'L18': 'item3Where',
        'A19': 'item4Code',
        'H19': 'item4Quantity',
        'K19': 'item4UsedFor',
        'L19': 'item4Where',
        'A20': 'item5Code',
        'H20': 'item5Quantity',
        'K20': 'item5UsedFor',
        'L20': 'item5Where',
        'A21': 'item6Code',
        'H21': 'item6Quantity',
        'K21': 'item6UsedFor',
        'L21': 'item6Where',
        'A22': 'item7Code',
        'H22': 'item7Quantity',
        'K22': 'item7UsedFor',
        'L22': 'item7Where',
        'A23': 'item8Code',
        'H23': 'item8Quantity',
        'K23': 'item8UsedFor',
        'L23': 'item8Where',
        'A24': 'item9Code',
        'H24': 'item9Quantity',
        'K24': 'item9UsedFor',
        'L24': 'item9Where',
        'A25': 'item10Code',
        'H25': 'item10Quantity',
        'K25': 'item10UsedFor',
        'L25': 'item10Where',
        'A26': 'item11Code',
        'H26': 'item11Quantity',
        'K26': 'item11UsedFor',
        'L26': 'item11Where',
        'A27': 'item12Code',
        'H27': 'item12Quantity',
        'K27': 'item12UsedFor',
        'L27': 'item12Where',
        'A28': 'item13Code',
        'H28': 'item13Quantity',
        'K28': 'item13UsedFor',
        'L28': 'item13Where',
        'A29': 'item14Code',
        'H29': 'item14Quantity',
        'K29': 'item14UsedFor',
        'L29': 'item14Where',
        'A30': 'item15Code',
        'H30': 'item15Quantity',
        'K30': 'item15UsedFor',
        'L30': 'item15Where',
      },
    },
    'Electric': {
      'templateFileId': '11wnDIr4gj628tT0z-QbfWliPz79I_kH7_2rOCiyjkz0',
      'sheetName': 'Ele',
      'cells': {
        'C3': 'location',
        'G3': 'siteName',
        'J3': 'siteCode',
        'I2': 'date',
        'C4': 'cmType',
        'H4': 'cmCategory',
        'K4': 'extraType',
        'A6': 'time',
        'C7': 'tech name',
        'C8': 'escalated',
        'C9': 'engineer name',
        'H6': 'G1',
        'H7': 'G2',
        'H9': 'CP',
        'J9': 'Kwh',
        'J6': 'T1',
        'J7': 'T2',
        'J8': 'T3',
        'A13': 'Comments1',
        'A16': 'item1Code',
        'H16': 'item1Quantity',
        'K16': 'item1UsedFor',
        'A17': 'item2Code',
        'H17': 'item2Quantity',
        'K17': 'item2UsedFor',
        'A18': 'item3Code',
        'H18': 'item3Quantity',
        'K18': 'item3UsedFor',
        'A19': 'item4Code',
        'H19': 'item4Quantity',
        'K19': 'item4UsedFor',
        'A20': 'item5Code',
        'H20': 'item5Quantity',
        'K20': 'item5UsedFor',
        'A21': 'item6Code',
        'H21': 'item6Quantity',
        'K21': 'item6UsedFor',
        'A22': 'item7Code',
        'H22': 'item7Quantity',
        'K22': 'item7UsedFor',
        'A23': 'item8Code',
        'H23': 'item8Quantity',
        'K23': 'item8UsedFor',
        'A24': 'item9Code',
        'H24': 'item9Quantity',
        'K24': 'item9UsedFor',
        'A25': 'item10Code',
        'H25': 'item10Quantity',
        'K25': 'item10UsedFor',
        'A26': 'item11Code',
        'H26': 'item11Quantity',
        'K26': 'item11UsedFor',
        'A27': 'item12Code',
        'H27': 'item12Quantity',
        'K27': 'item12UsedFor',
        'A28': 'item13Code',
        'H28': 'item13Quantity',
        'K28': 'item13UsedFor',
      },
    },
    'AC': {
      'templateFileId': '1g3nXr3AJCL1KnmLFuCrvN7zm-zWK4GVzr1GF16aBUL8',
      'sheetName': 'AC',
      'cells': {
        'C3': 'location',
        'G3': 'siteName',
        'J3': 'siteCode',
        'I2': 'date',
        'C4': 'cmType',
        'H4': 'cmCategory',
        'K4': 'extraType',
        'D6': 'time',
        'F7': 'tech name',
        'F8': 'escalated',
        'F9': 'engineer name',
        'H6': 'G1',
        'H7': 'G2',
        'H9': 'CP',
        'J9': 'Kwh',
        'J6': 'T1',
        'J7': 'T2',
        'J8': 'T3',
        'A14': 'Comments1',
        'F14': 'Comments2',
        'A16': 'item1Code',
        'H16': 'item1Quantity',
        'K16': 'item1UsedFor',
        'L16': 'item1Where',
        'A17': 'item2Code',
        'H17': 'item2Quantity',
        'K17': 'item2UsedFor',
        'L17': 'item2Where',
        'A18': 'item3Code',
        'H18': 'item3Quantity',
        'K18': 'item3UsedFor',
        'L18': 'item3Where',
        'A19': 'item4Code',
        'H19': 'item4Quantity',
        'K19': 'item4UsedFor',
        'L19': 'item4Where',
        'A20': 'item5Code',
        'H20': 'item5Quantity',
        'K20': 'item5UsedFor',
        'L20': 'item5Where',
        'A21': 'item6Code',
        'H21': 'item6Quantity',
        'K21': 'item6UsedFor',
        'L21': 'item6Where',
        'A22': 'item7Code',
        'H22': 'item7Quantity',
        'K22': 'item7UsedFor',
        'L22': 'item7Where',
        'A23': 'item8Code',
        'H23': 'item8Quantity',
        'K23': 'item8UsedFor',
        'L23': 'item8Where',
        'A24': 'item9Code',
        'H24': 'item9Quantity',
        'K24': 'item9UsedFor',
        'L24': 'item9Where',
        'A25': 'item10Code',
        'H25': 'item10Quantity',
        'K25': 'item10UsedFor',
        'L25': 'item10Where',
        'A26': 'item11Code',
        'H26': 'item11Quantity',
        'K26': 'item11UsedFor',
        'L26': 'item11Where',
        'A27': 'item12Code',
        'H27': 'item12Quantity',
        'K27': 'item12UsedFor',
        'L27': 'item12Where',
        'A28': 'item13Code',
        'H28': 'item13Quantity',
        'K28': 'item13UsedFor',
        'L28': 'item13Where',
        'A29': 'item14Code',
        'H29': 'item14Quantity',
        'K29': 'item14UsedFor',
        'L29': 'item14Where',
        'A30': 'item15Code',
        'H30': 'item15Quantity',
        'K30': 'item15UsedFor',
        'L30': 'item15Where',
      },
    },
    'Civil': {
      'templateFileId': '1MVbogaeQKVjAMiQJZHycBx1MstVIjX6YFQv5T4hJbfU',
      'sheetName': 'Civil',
      'cells': {
        'C3': 'location',
        'G3': 'siteName',
        'J3': 'siteCode',
        'I2': 'date',
        'C4': 'cmType',
        'H4': 'cmCategory',
        'K4': 'extraType',
        'D6': 'time',
        'F7': 'tech name',
        'F8': 'escalated',
        'F9': 'engineer name',
        'H6': 'G1',
        'H7': 'G2',
        'H9': 'CP',
        'J9': 'Kwh',
        'J6': 'T1',
        'J7': 'T2',
        'J8': 'T3',
        'A16': 'Comments1',
        'A18': 'item1Code',
        'H18': 'item1Quantity',
        'K18': 'item1UsedFor',
        'A19': 'item2Code',
        'H19': 'item2Quantity',
        'K19': 'item2UsedFor',
        'A20': 'item3Code',
        'H20': 'item3Quantity',
        'K20': 'item3UsedFor',
        'A21': 'item4Code',
        'H21': 'item4Quantity',
        'K21': 'item4UsedFor',
        'A22': 'item5Code',
        'H22': 'item5Quantity',
        'K22': 'item5UsedFor',
        'A23': 'item6Code',
        'H23': 'item6Quantity',
        'K23': 'item6UsedFor',
        'A24': 'item7Code',
        'H24': 'item7Quantity',
        'K24': 'item7UsedFor',
        'A25': 'item8Code',
        'H25': 'item8Quantity',
        'K25': 'item8UsedFor',
        'A26': 'item9Code',
        'H26': 'item9Quantity',
        'K26': 'item9UsedFor',
        'A27': 'item10Code',
        'H27': 'item10Quantity',
        'K27': 'item10UsedFor',
        'A28': 'item11Code',
        'H28': 'item11Quantity',
        'K28': 'item11UsedFor',
        'A29': 'item12Code',
        'H29': 'item12Quantity',
        'K29': 'item12UsedFor',
        'A30': 'item13Code',
        'H30': 'item13Quantity',
        'K30': 'item13UsedFor',
        'A31': 'item14Code',
        'H31': 'item14Quantity',
        'K31': 'item14UsedFor',
        'A32': 'item15Code',
        'H32': 'item15Quantity',
        'K32': 'item15UsedFor',
      },
    },
    // Add other types as needed
  };

  Map<String, dynamic> getCMMapping(String sheetType) {
    if (sheetMappings.containsKey(sheetType)) {
      return sheetMappings[sheetType]!['cells'] as Map<String, dynamic>;
    } else {
      throw Exception('Invalid sheet type');
    }
  }

  String getCMTemplateFileId(String sheetType) {
    if (sheetMappings.containsKey(sheetType)) {
      return sheetMappings[sheetType]!['templateFileId'] as String;
    } else {
      throw Exception('Invalid sheet type');
    }
  }

  String getCMSheetName(String sheetType) {
    if (sheetMappings.containsKey(sheetType)) {
      return sheetMappings[sheetType]!['sheetName'] as String;
    } else {
      throw Exception('Invalid sheet type');
    }
  }
}
