class SheetMapper {
  final Map<int, Map<String, dynamic>> sheetMappings = {
    1: {
      'templateFileId': '1yYzm6L16R72hVjH9rsag5O-fr4yjwFsghf4aXf9N4sY',
      'sheetName': '1',
      'cells': {
        //First Section
        'BF8': 'siteName',
        'AG8': 'date',
        'L9': 'location',
        'AG9': 'timeIn',
        'BF9': 'timeOut',
        'AG10': 'CP',
        'BF10': 'Kwh',
        'L12': 'Main v1',
        'AG12': 'Main v2',
        'BF12': 'Main v3',
        'L13': 'Main l1',
        'AG13': 'Main l2',
        'BF13': 'Main l3',
        'L14': 'HP',
        'AG14': 'LP',
        'BF14': 'room temp',
        'L15': 'generalComments',
        //G1,G2 Section
        'I20': 'G1',
        'N20': 'cycleForG1',
        'AB20': 'gen1 battery',
        'AF20': 'gen1 load 1',
        'AJ20': 'gen1 load 2',
        'AP20': 'gen1 load 3',
        'AS20': 'gen1 voltage ph-n1',
        'AY20': 'gen1 voltage ph-n2',
        'BC20': 'gen1 voltage ph-n3',
        'BD20': 'gen1 voltage ph-l1',
        'BH20': 'gen1 voltage ph-l2',
        'BK20': 'gen1 voltage ph-l3',
        'I21': 'g1Comments',
        'I22': 'G2',
        'N22': 'cycleForG2',
        'AB22': 'gen2 battery',
        'AF22': 'gen1 load 1',
        'AJ22': 'gen1 load 2',
        'AP22': 'gen1 load 3',
        'AS22': 'gen2 voltage ph-n1',
        'AY22': 'gen2 voltage ph-n2',
        'BC22': 'gen2 voltage ph-n3',
        'BD22': 'gen2 voltage ph-l1',
        'BH22': 'gen2 voltage ph-l2',
        'BK22': 'gen2 voltage ph-l3',
        'I23': 'g2Comments',
        //Replacement Section
        'Z27': 'g1 oil',
        'Z28': 'g1 oil',
        'Z29': 'g1 oil',
        'Z30': 'g1 gen sep',
        'Z31': 'g1 tank sep',
        'Z32': 'g1 air',
        'Z33': 'g1 coolant',
        'Z34': 'clean g1 air',
        'AN27': 'g2 oil',
        'AN28': 'g2 oil',
        'AN29': 'g2 oil',
        'AN30': 'g2 gen sep',
        'AN31': 'g2 tank sep',
        'AN32': 'g2 air',
        'AN33': 'g2 coolant',
        'AN34': 'clean g2 air',
        //AC Section
        'J50': 'ac1 volt',
        'J52': 'ac2 volt',
        'J54': 'ac3 volt',
        'AK50': 'ac1 load',
        'AK52': 'ac2 load',
        'AK54': 'ac3 load',
        'J55': 'acComments',
        //Electric Section
        'K69': 'Main v1',
        'AC69': 'Main v2',
        'BA69': 'Main v3',
        'K70': 'gen earth',
        'AC70': 'light earth',
        'BA70': 'tel earth',
        'BA71': 'leg earth',
        'K71': 'start dc',
        'AC71': 'end dc',
        'K72': 'fire',
        'AC72': 'owner load',
        'BA72': 'neighbor load',
        'AC73': '3rd load',
        'K74': 'electricComments',
        'AL80': 'battery test',
        //Fuel Section
        'M90': 'T1 shape',
        'M91': 'T2 shape',
        'M92': 'T3 shape',
        'S90': 'T1',
        'S91': 'T2',
        'S92': 'T3',
        'H95': 'engineer name'
      },
    },
    2: {
      'templateFileId': '1H4zlwpXqAPQYbrBnYWy7EnarbX-yifYs17ubfhM1zIE',
      'sheetName': '2',
      'cells': {
        //First Section
        'BF8': 'siteName',
        'AG8': 'date',
        'L9': 'location',
        'AG9': 'timeIn',
        'BF9': 'timeOut',
        'AG10': 'CP',
        'BF10': 'Kwh',
        'L12': 'Main v1',
        'AG12': 'Main v2',
        'BF12': 'Main v3',
        'L13': 'Main l1',
        'AG13': 'Main l2',
        'BF13': 'Main l3',
        'L14': 'HP',
        'AG14': 'LP',
        'BF14': 'room temp',
        'L15': 'generalComments',
        //G1,G2 Section
        'I20': 'G1',
        'N20': 'cycleForG1',
        'AB20': 'gen1 battery',
        'AF20': 'gen1 load 1',
        'AJ20': 'gen1 load 2',
        'AP20': 'gen1 load 3',
        'AS20': 'gen1 voltage ph-n1',
        'AY20': 'gen1 voltage ph-n2',
        'BC20': 'gen1 voltage ph-n3',
        'BD20': 'gen1 voltage ph-l1',
        'BH20': 'gen1 voltage ph-l2',
        'BK20': 'gen1 voltage ph-l3',
        'I21': 'g1Comments',
        'I22': 'G2',
        'N22': 'cycleForG2',
        'AB22': 'gen2 battery',
        'AF22': 'gen1 load 1',
        'AJ22': 'gen1 load 2',
        'AP22': 'gen1 load 3',
        'AS22': 'gen2 voltage ph-n1',
        'AY22': 'gen2 voltage ph-n2',
        'BC22': 'gen2 voltage ph-n3',
        'BD22': 'gen2 voltage ph-l1',
        'BH22': 'gen2 voltage ph-l2',
        'BK22': 'gen2 voltage ph-l3',
        'I23': 'g2Comments',
        //Replacement Section
        'Z27': 'g1 oil',
        'Z28': 'g1 oil',
        'Z29': 'g1 oil',
        'Z30': 'g1 gen sep',
        'Z31': 'g1 tank sep',
        'Z32': 'g1 air',
        'Z33': 'g1 coolant',
        'Z34': 'clean g1 air',
        'AN27': 'g2 oil',
        'AN28': 'g2 oil',
        'AN29': 'g2 oil',
        'AN30': 'g2 gen sep',
        'AN31': 'g2 tank sep',
        'AN32': 'g2 air',
        'AN33': 'g2 coolant',
        'AN34': 'clean g2 air',
        //AC Section
        'J50': 'ac1 volt',
        'J52': 'ac2 volt',
        'J54': 'ac3 volt',
        'AK50': 'ac1 load',
        'AK52': 'ac2 load',
        'AK54': 'ac3 load',
        'J55': 'acComments',
        //Electric Section
        'K69': 'Main v1',
        'AC69': 'Main v2',
        'BA69': 'Main v3',
        'K70': 'gen earth',
        'AC70': 'light earth',
        'BA70': 'tel earth',
        'BA71': 'leg earth',
        'K71': 'start dc',
        'AC71': 'end dc',
        'K72': 'fire',
        'AC72': 'owner load',
        'BA72': 'neighbor load',
        'AC73': '3rd load',
        'K74': 'electricComments',
        'AL80': 'battery test',
        //Fuel Section
        'M90': 'T1 shape',
        'M91': 'T2 shape',
        'S90': 'T1',
        'S91': 'T2',
        'H93': 'engineer name'
      },
    },
    3: {
      'templateFileId': '1O8wViUozGPOmF72Yq64nP1Y2J9-u48SYWy60q8fVx9U',
      'sheetName': '3',
      'cells': {
        //First Section
        'BF8': 'siteName',
        'AG8': 'date',
        'L9': 'location',
        'AG9': 'timeIn',
        'BF9': 'timeOut',
        'AG10': 'CP',
        'BF10': 'Kwh',
        'L12': 'Main v1',
        'AG12': 'Main v2',
        'BF12': 'Main v3',
        'L13': 'Main l1',
        'AG13': 'Main l2',
        'BF13': 'Main l3',
        'L14': 'HP',
        'AG14': 'LP',
        'BF14': 'room temp',
        'L15': 'generalComments',
        //G1,G2 Section
        'I20': 'G1',
        'N20': 'cycleForG1',
        'AB20': 'gen1 battery',
        'AF20': 'gen1 load 1',
        'AJ20': 'gen1 load 2',
        'AP20': 'gen1 load 3',
        'AS20': 'gen1 voltage ph-n1',
        'AY20': 'gen1 voltage ph-n2',
        'BC20': 'gen1 voltage ph-n3',
        'BD20': 'gen1 voltage ph-l1',
        'BH20': 'gen1 voltage ph-l2',
        'BK20': 'gen1 voltage ph-l3',
        'I21': 'g1Comments',
        'I22': 'G2',
        'N22': 'cycleForG2',
        'AB22': 'gen2 battery',
        'AF22': 'gen1 load 1',
        'AJ22': 'gen1 load 2',
        'AP22': 'gen1 load 3',
        'AS22': 'gen2 voltage ph-n1',
        'AY22': 'gen2 voltage ph-n2',
        'BC22': 'gen2 voltage ph-n3',
        'BD22': 'gen2 voltage ph-l1',
        'BH22': 'gen2 voltage ph-l2',
        'BK22': 'gen2 voltage ph-l3',
        'I23': 'g2Comments',
        //Replacement Section
        'Z27': 'g1 oil',
        'Z28': 'g1 oil',
        'Z29': 'g1 oil',
        'Z30': 'g1 gen sep',
        'Z31': 'g1 tank sep',
        'Z32': 'g1 air',
        'Z33': 'g1 coolant',
        'Z34': 'clean g1 air',
        'AN27': 'g2 oil',
        'AN28': 'g2 oil',
        'AN29': 'g2 oil',
        'AN30': 'g2 gen sep',
        'AN31': 'g2 tank sep',
        'AN32': 'g2 air',
        'AN33': 'g2 coolant',
        'AN34': 'clean g2 air',
        //AC Section
        'J50': 'ac1 volt',
        'J52': 'ac2 volt',
        'J54': 'ac3 volt',
        'AK50': 'ac1 load',
        'AK52': 'ac2 load',
        'AK54': 'ac3 load',
        'J55': 'acComments',
        //Electric Section
        'K69': 'Main v1',
        'AC69': 'Main v2',
        'BA69': 'Main v3',
        'K70': 'gen earth',
        'AC70': 'light earth',
        'BA70': 'tel earth',
        'BA71': 'leg earth',
        'K71': 'start dc',
        'AC71': 'end dc',
        'K72': 'fire',
        'AC72': 'owner load',
        'BA72': 'neighbor load',
        'AC73': '3rd load',
        'K74': 'electricComments',
        'AL80': 'battery test',
        //Fuel Section
        'M90': 'T1 shape',
        'S90': 'T1',
        'H92': 'engineer name'
      },
    },
    4: {
      'templateFileId': '1xfbIfLBuZ2dTocoSmWJcYxj645kbpe6FNwBYzK7ycNk',
      'sheetName': '4',
      'cells': {
        //First Section
        'BF8': 'siteName',
        'AG8': 'date',
        'L9': 'location',
        'AG9': 'timeIn',
        'BF9': 'timeOut',
        'AG10': 'CP',
        'BF10': 'Kwh',
        'L12': 'Main v1',
        'AG12': 'Main v2',
        'BF12': 'Main v3',
        'L13': 'Main l1',
        'AG13': 'Main l2',
        'BF13': 'Main l3',
        'L14': 'HP',
        'AG14': 'LP',
        'BF14': 'room temp',
        'L15': 'generalComments',
        //G1,G2 Section
        'I20': 'G1',
        'N20': 'cycleForG1',
        'AB20': 'gen1 battery',
        'AF20': 'gen1 load 1',
        'AJ20': 'gen1 load 2',
        'AQ20': 'gen1 load 3',
        'AS20': 'gen1 voltage ph-n1',
        'AY20': 'gen1 voltage ph-n2',
        'BC20': 'gen1 voltage ph-n3',
        'BD20': 'gen1 voltage ph-l1',
        'BH20': 'gen1 voltage ph-l2',
        'BK20': 'gen1 voltage ph-l3',
        'I21': 'g1Comments',
        'I22': 'G2',
        'N22': 'cycleForG2',
        'AB22': 'gen2 battery',
        'AF22': 'gen1 load 1',
        'AJ22': 'gen1 load 2',
        'AQ22': 'gen1 load 3',
        'AS22': 'gen2 voltage ph-n1',
        'AY22': 'gen2 voltage ph-n2',
        'BC22': 'gen2 voltage ph-n3',
        'BD22': 'gen2 voltage ph-l1',
        'BH22': 'gen2 voltage ph-l2',
        'BK22': 'gen2 voltage ph-l3',
        'I23': 'g2Comments',
        //Replacement Section
        'Z27': 'g1 oil',
        'Z28': 'g1 oil',
        'Z29': 'g1 oil',
        'Z30': 'g1 gen sep',
        'Z31': 'g1 tank sep',
        'Z32': 'g1 air',
        'Z33': 'g1 coolant',
        'Z34': 'clean g1 air',
        'AO27': 'g2 oil',
        'AO28': 'g2 oil',
        'AO29': 'g2 oil',
        'AO30': 'g2 gen sep',
        'AO31': 'g2 tank sep',
        'AO32': 'g2 air',
        'AO33': 'g2 coolant',
        'AO34': 'clean g2 air',
        //AC Section
        'J50': 'ac1 volt',
        'J52': 'ac2 volt',
        'AK50': 'ac1 load',
        'AK52': 'ac2 load',
        'J53': 'acComments',
        //Electric Section
        'K68': 'Main v1',
        'AC68': 'Main v2',
        'BA68': 'Main v3',
        'K69': 'gen earth',
        'AC69': 'light earth',
        'BA69': 'tel earth',
        'BA70': 'leg earth',
        'K70': 'start dc',
        'AC70': 'end dc',
        'K71': 'fire',
        'AC71': 'owner load',
        'BA71': 'neighbor load',
        'AC72': '3rd load',
        'K73': 'electricComments',
        'AL79': 'battery test',
        //Fuel Section
        'M89': 'T1 shape',
        'M90': 'T2 shape',
        'S89': 'T1',
        'S90': 'T2',
        'H92': 'engineer name'
      },
    },
    5: {
      'templateFileId': '1c9podSRIiNs8MJaHxhF3AG-k33nDCPcMkmlWuySXDCk',
      'sheetName': '5',
      'cells': {
        //First Section
        'BF8': 'siteName',
        'AG8': 'date',
        'L9': 'location',
        'AG9': 'timeIn',
        'BF9': 'timeOut',
        'AG10': 'CP',
        'BF10': 'Kwh',
        'L12': 'Main v1',
        'AG12': 'Main v2',
        'BF12': 'Main v3',
        'L13': 'Main l1',
        'AG13': 'Main l2',
        'BF13': 'Main l3',
        'L14': 'HP',
        'AG14': 'LP',
        'BF14': 'room temp',
        'L15': 'generalComments',
        //G1,G2 Section
        'I20': 'G1',
        'N20': 'cycleForG1',
        'AB20': 'gen1 battery',
        'AF20': 'gen1 load 1',
        'AJ20': 'gen1 load 2',
        'AQ20': 'gen1 load 3',
        'AS20': 'gen1 voltage ph-n1',
        'AY20': 'gen1 voltage ph-n2',
        'BC20': 'gen1 voltage ph-n3',
        'BD20': 'gen1 voltage ph-l1',
        'BH20': 'gen1 voltage ph-l2',
        'BK20': 'gen1 voltage ph-l3',
        'I21': 'g1Comments',
        'I22': 'G2',
        'N22': 'cycleForG2',
        'AB22': 'gen2 battery',
        'AF22': 'gen1 load 1',
        'AJ22': 'gen1 load 2',
        'AQ22': 'gen1 load 3',
        'AS22': 'gen2 voltage ph-n1',
        'AY22': 'gen2 voltage ph-n2',
        'BC22': 'gen2 voltage ph-n3',
        'BD22': 'gen2 voltage ph-l1',
        'BH22': 'gen2 voltage ph-l2',
        'BK22': 'gen2 voltage ph-l3',
        'I23': 'g2Comments',
        //Replacement Section
        'Z27': 'g1 oil',
        'Z28': 'g1 oil',
        'Z29': 'g1 oil',
        'Z30': 'g1 gen sep',
        'Z31': 'g1 tank sep',
        'Z32': 'g1 air',
        'Z33': 'g1 coolant',
        'Z34': 'clean g1 air',
        'AO27': 'g2 oil',
        'AO28': 'g2 oil',
        'AO29': 'g2 oil',
        'AO30': 'g2 gen sep',
        'AO31': 'g2 tank sep',
        'AO32': 'g2 air',
        'AO33': 'g2 coolant',
        'AO34': 'clean g2 air',
        //AC Section
        'J50': 'ac1 volt',
        'J52': 'ac2 volt',
        'AK50': 'ac1 load',
        'AK52': 'ac2 load',
        'J53': 'acComments',
        //Electric Section
        'K68': 'Main v1',
        'AC68': 'Main v2',
        'BA68': 'Main v3',
        'K69': 'gen earth',
        'AC69': 'light earth',
        'BA69': 'tel earth',
        'BA70': 'leg earth',
        'K70': 'start dc',
        'AC70': 'end dc',
        'K71': 'fire',
        'AC71': 'owner load',
        'BA71': 'neighbor load',
        'AC72': '3rd load',
        'K73': 'electricComments',
        'AL79': 'battery test',
        //Fuel Section
        'M89': 'T1 shape',
        'S89': 'T1',
        'H91': 'engineer name'
      },
    },
    6: {
      'templateFileId': '1HCHukt2UPZWaMAkzWc7WSglvQ14bV76Kg3_DtbYx9so',
      'sheetName': '6',
      'cells': {
        //First Section
        'BF8': 'siteName',
        'AG8': 'date',
        'L9': 'location',
        'AG9': 'timeIn',
        'BF9': 'timeOut',
        'AG10': 'CP',
        'BF10': 'Kwh',
        'L12': 'Main v1',
        'AG12': 'Main v2',
        'BF12': 'Main v3',
        'L13': 'Main l1',
        'AG13': 'Main l2',
        'BF13': 'Main l3',
        'L14': 'HP',
        'AG14': 'LP',
        'BF14': 'room temp',
        'L15': 'generalComments',
        //G1,G2 Section
        'I20': 'G1',
        'N20': 'cycleForG1',
        'AB20': 'gen1 battery',
        'AF20': 'gen1 load 1',
        'AJ20': 'gen1 load 2',
        'AQ20': 'gen1 load 3',
        'AS20': 'gen1 voltage ph-n1',
        'AY20': 'gen1 voltage ph-n2',
        'BC20': 'gen1 voltage ph-n3',
        'BD20': 'gen1 voltage ph-l1',
        'BH20': 'gen1 voltage ph-l2',
        'BK20': 'gen1 voltage ph-l3',
        'I21': 'g1Comments',
        'I22': 'G2',
        'N22': 'cycleForG2',
        'AB22': 'gen2 battery',
        'AF22': 'gen1 load 1',
        'AJ22': 'gen1 load 2',
        'AQ22': 'gen1 load 3',
        'AS22': 'gen2 voltage ph-n1',
        'AY22': 'gen2 voltage ph-n2',
        'BC22': 'gen2 voltage ph-n3',
        'BD22': 'gen2 voltage ph-l1',
        'BH22': 'gen2 voltage ph-l2',
        'BK22': 'gen2 voltage ph-l3',
        'I23': 'g2Comments',
        //Replacement Section
        'Z27': 'g1 oil',
        'Z28': 'g1 oil',
        'Z29': 'g1 oil',
        'Z30': 'g1 gen sep',
        'Z31': 'g1 tank sep',
        'Z32': 'g1 air',
        'Z33': 'g1 coolant',
        'Z34': 'clean g1 air',
        'AO27': 'g2 oil',
        'AO28': 'g2 oil',
        'AO29': 'g2 oil',
        'AO30': 'g2 gen sep',
        'AO31': 'g2 tank sep',
        'AO32': 'g2 air',
        'AO33': 'g2 coolant',
        'AO34': 'clean g2 air',
        //AC Section
        'J50': 'ac3 volt',
        'AK50': 'ac3 load',
        'J52': 'outdoor volt',
        'AK52': 'outdoor load',
        'J51': 'acComments',
        //Electric Section
        'K68': 'Main v1',
        'AC68': 'Main v2',
        'BA68': 'Main v3',
        'K69': 'gen earth',
        'AC69': 'light earth',
        'BA69': 'tel earth',
        'BA70': 'leg earth',
        'K70': 'start dc',
        'AC70': 'end dc',
        'K71': 'fire',
        'AC71': 'owner load',
        'BA71': 'neighbor load',
        'AC72': '3rd load',
        'K73': 'electricComments',
        'AL79': 'battery test',
        //Fuel Section
        'M89': 'T1 shape',
        'M90': 'T2 shape',
        'S89': 'T1',
        'S90': 'T2',
        'H92': 'engineer name'
      },
    },
    7: {
      'templateFileId': '1wLRfDiI1_LIhJNzjnHcjtonjnoqbzVoulFnqlXKAGps',
      'sheetName': '7',
      'cells': {
        //First Section
        'BF8': 'siteName',
        'AG8': 'date',
        'L9': 'location',
        'AG9': 'timeIn',
        'BF9': 'timeOut',
        'AG10': 'CP',
        'BF10': 'Kwh',
        'L12': 'Main v1',
        'AG12': 'Main v2',
        'BF12': 'Main v3',
        'L13': 'Main l1',
        'AG13': 'Main l2',
        'BF13': 'Main l3',
        'L14': 'HP',
        'AG14': 'LP',
        'BF14': 'room temp',
        'L15': 'generalComments',
        //G1,G2 Section
        'I20': 'G1',
        'N20': 'cycleForG1',
        'AB20': 'gen1 battery',
        'AF20': 'gen1 load 1',
        'AJ20': 'gen1 load 2',
        'AQ20': 'gen1 load 3',
        'AS20': 'gen1 voltage ph-n1',
        'AY20': 'gen1 voltage ph-n2',
        'BC20': 'gen1 voltage ph-n3',
        'BD20': 'gen1 voltage ph-l1',
        'BH20': 'gen1 voltage ph-l2',
        'BK20': 'gen1 voltage ph-l3',
        'I21': 'g1Comments',
        'I22': 'G2',
        'N22': 'cycleForG2',
        'AB22': 'gen2 battery',
        'AF22': 'gen1 load 1',
        'AJ22': 'gen1 load 2',
        'AQ22': 'gen1 load 3',
        'AS22': 'gen2 voltage ph-n1',
        'AY22': 'gen2 voltage ph-n2',
        'BC22': 'gen2 voltage ph-n3',
        'BD22': 'gen2 voltage ph-l1',
        'BH22': 'gen2 voltage ph-l2',
        'BK22': 'gen2 voltage ph-l3',
        'I23': 'g2Comments',
        //Replacement Section
        'Z27': 'g1 oil',
        'Z28': 'g1 oil',
        'Z29': 'g1 oil',
        'Z30': 'g1 gen sep',
        'Z31': 'g1 tank sep',
        'Z32': 'g1 air',
        'Z33': 'g1 coolant',
        'Z34': 'clean g1 air',
        'AO27': 'g2 oil',
        'AO28': 'g2 oil',
        'AO29': 'g2 oil',
        'AO30': 'g2 gen sep',
        'AO31': 'g2 tank sep',
        'AO32': 'g2 air',
        'AO33': 'g2 coolant',
        'AO34': 'clean g2 air',
        //AC Section
        'J50': 'ac3 volt',
        'AK50': 'ac3 load',
        'J52': 'outdoor volt',
        'AK52': 'outdoor load',
        'J51': 'acComments',
        //Electric Section
        'K68': 'Main v1',
        'AC68': 'Main v2',
        'BA68': 'Main v3',
        'K69': 'gen earth',
        'AC69': 'light earth',
        'BA69': 'tel earth',
        'BA70': 'leg earth',
        'K70': 'start dc',
        'AC70': 'end dc',
        'K71': 'fire',
        'AC71': 'owner load',
        'BA71': 'neighbor load',
        'AC72': '3rd load',
        'K73': 'electricComments',
        'AL79': 'battery test',
        //Fuel Section
        'M89': 'T1 shape',
        'S89': 'T1',
        'H91': 'engineer name'
      },
    },
    8: {
      'templateFileId': '1z8Z3NAtHMdmlJlKcuf7lER3g3JiAtaoEFL-RJiS-14M',
      'sheetName': '8',
      'cells': {
        //First Section
        'BD8': 'siteName',
        'AG8': 'date',
        'L9': 'location',
        'AG9': 'timeIn',
        'BD9': 'timeOut',
        'AG10': 'CP',
        'BD10': 'Kwh',
        'L12': 'Main v1',
        'AG12': 'Main v2',
        'BD12': 'Main v3',
        'L13': 'Main l1',
        'AG13': 'Main l2',
        'BD13': 'Main l3',
        'L14': 'HP',
        'AG14': 'LP',
        'BD14': 'room temp',
        'L15': 'generalComments',
        //G1,G2 Section
        'I20': 'G1',
        'N20': 'cycleForG1',
        'AB20': 'gen1 battery',
        'AF20': 'gen1 load 1',
        'AJ20': 'gen1 load 2',
        'AO20': 'gen1 load 3',
        'AQ20': 'gen1 voltage ph-n1',
        'AW20': 'gen1 voltage ph-n2',
        'BA20': 'gen1 voltage ph-n3',
        'BB20': 'gen1 voltage ph-l1',
        'BF20': 'gen1 voltage ph-l2',
        'BI20': 'gen1 voltage ph-l3',
        'I21': 'g1Comments',
        'I22': 'G2',
        'N22': 'cycleForG2',
        'AB22': 'gen2 battery',
        'AF22': 'gen1 load 1',
        'AJ22': 'gen1 load 2',
        'AO22': 'gen1 load 3',
        'AQ22': 'gen2 voltage ph-n1',
        'AW22': 'gen2 voltage ph-n2',
        'BA22': 'gen2 voltage ph-n3',
        'BB22': 'gen2 voltage ph-l1',
        'BF22': 'gen2 voltage ph-l2',
        'BI22': 'gen2 voltage ph-l3',
        'I23': 'g2Comments',
        //Replacement Section
        'Z27': 'g1 oil',
        'Z28': 'g1 oil',
        'Z29': 'g1 oil',
        'Z30': 'g1 gen sep',
        'Z31': 'g1 tank sep',
        'Z32': 'g1 air',
        'Z33': 'g1 coolant',
        'Z34': 'clean g1 air',
        'AM27': 'g2 oil',
        'AM28': 'g2 oil',
        'AM29': 'g2 oil',
        'AM30': 'g2 gen sep',
        'AM31': 'g2 tank sep',
        'AM32': 'g2 air',
        'AM33': 'g2 coolant',
        'AM34': 'clean g2 air',
        //AC Section
        'J50': 'outdoor volt',
        'AK50': 'outdoor load',
        'J51': 'acComments',
        //Electric Section
        'K65': 'Main v1',
        'AC65': 'Main v2',
        'AY65': 'Main v3',
        'K66': 'gen earth',
        'AC66': 'light earth',
        'AY66': 'tel earth',
        'AY67': 'leg earth',
        'K67': 'start dc',
        'AC67': 'end dc',
        'K68': 'fire',
        'AC68': 'owner load',
        'AY68': 'neighbor load',
        'AC69': '3rd load',
        'K70': 'electricComments',
        'AL76': 'battery test',
        //Fuel Section
        'M86': 'T1 shape',
        'M87': 'T2 shape',
        'S86': 'T1',
        'S87': 'T2',
        'H89': 'engineer name'
      },
    },
    9: {
      'templateFileId': '1GbLBkKMk7H15YK6Odd0ktBzLoLJFUbQe19rFiqfNqIQ',
      'sheetName': '9',
      'cells': {
        //First Section
        'BD8': 'siteName',
        'AG8': 'date',
        'L9': 'location',
        'AG9': 'timeIn',
        'BD9': 'timeOut',
        'AG10': 'CP',
        'BD10': 'Kwh',
        'L12': 'Main v1',
        'AG12': 'Main v2',
        'BD12': 'Main v3',
        'L13': 'Main l1',
        'AG13': 'Main l2',
        'BD13': 'Main l3',
        'L14': 'HP',
        'AG14': 'LP',
        'BD14': 'room temp',
        'L15': 'generalComments',
        //G1,G2 Section
        'I20': 'G1',
        'N20': 'cycleForG1',
        'AB20': 'gen1 battery',
        'AF20': 'gen1 load 1',
        'AJ20': 'gen1 load 2',
        'AO20': 'gen1 load 3',
        'AQ20': 'gen1 voltage ph-n1',
        'AW20': 'gen1 voltage ph-n2',
        'BA20': 'gen1 voltage ph-n3',
        'BB20': 'gen1 voltage ph-l1',
        'BF20': 'gen1 voltage ph-l2',
        'BI20': 'gen1 voltage ph-l3',
        'I21': 'g1Comments',
        'I22': 'G2',
        'N22': 'cycleForG2',
        'AB22': 'gen2 battery',
        'AF22': 'gen1 load 1',
        'AJ22': 'gen1 load 2',
        'AO22': 'gen1 load 3',
        'AQ22': 'gen2 voltage ph-n1',
        'AW22': 'gen2 voltage ph-n2',
        'BA22': 'gen2 voltage ph-n3',
        'BB22': 'gen2 voltage ph-l1',
        'BF22': 'gen2 voltage ph-l2',
        'BI22': 'gen2 voltage ph-l3',
        'I23': 'g2Comments',
        //Replacement Section
        'Z27': 'g1 oil',
        'Z28': 'g1 oil',
        'Z29': 'g1 oil',
        'Z30': 'g1 gen sep',
        'Z31': 'g1 tank sep',
        'Z32': 'g1 air',
        'Z33': 'g1 coolant',
        'Z34': 'clean g1 air',
        'AM27': 'g2 oil',
        'AM28': 'g2 oil',
        'AM29': 'g2 oil',
        'AM30': 'g2 gen sep',
        'AM31': 'g2 tank sep',
        'AM32': 'g2 air',
        'AM33': 'g2 coolant',
        'AM34': 'clean g2 air',
        //AC Section
        'J50': 'outdoor volt',
        'AK50': 'outdoor load',
        'J51': 'acComments',
        //Electric Section
        'K65': 'Main v1',
        'AC65': 'Main v2',
        'AY65': 'Main v3',
        'K66': 'gen earth',
        'AC66': 'light earth',
        'AY66': 'tel earth',
        'AY67': 'leg earth',
        'K67': 'start dc',
        'AC67': 'end dc',
        'K68': 'fire',
        'AC68': 'owner load',
        'AY68': 'neighbor load',
        'AC69': '3rd load',
        'K70': 'electricComments',
        'AL76': 'battery test',
        //Fuel Section
        'M86': 'T1 shape',
        'S86': 'T1',
        'H88': 'engineer name'
      },
    },
    10: {
      'templateFileId': '1SXsvCG4JM2mLlPWeHK6QxPzQtOoWCgVcJXw5amw2OFA',
      'sheetName': '10',
      'cells': {
        //First Section
        'BE8': 'siteName',
        'AG8': 'date',
        'L9': 'location',
        'AG9': 'timeIn',
        'BE9': 'timeOut',
        'AG10': 'CP',
        'BE10': 'Kwh',
        'L12': 'Main v1',
        'AG12': 'Main v2',
        'BE12': 'Main v3',
        'L13': 'Main l1',
        'AG13': 'Main l2',
        'BE13': 'Main l3',
        'L14': 'HP',
        'AG14': 'LP',
        'BE14': 'room temp',
        'L15': 'generalComments',
        //G1,G2 Section
        'I20': 'G1',
        'N20': 'cycleForG1',
        'AB20': 'gen1 battery',
        'AF20': 'gen1 load 1',
        'AJ20': 'gen1 load 2',
        'AP20': 'gen1 load 3',
        'AS20': 'gen1 voltage ph-n1',
        'AX20': 'gen1 voltage ph-n2',
        'BA20': 'gen1 voltage ph-n3',
        'BC20': 'gen1 voltage ph-l1',
        'BG20': 'gen1 voltage ph-l2',
        'BI20': 'gen1 voltage ph-l3',
        'I21': 'g1Comments',
        //Replacement Section
        'Z24': 'g1 oil',
        'Z25': 'g1 oil',
        'Z26': 'g1 oil',
        'Z27': 'g1 gen sep',
        'Z28': 'g1 tank sep',
        'Z29': 'g1 air',
        'Z30': 'g1 coolant',
        'Z31': 'clean g1 air',
        //AC Section
        'J47': 'ac1 volt',
        'J49': 'ac2 volt',
        'J51': 'ac3 volt',
        'AK47': 'ac1 load',
        'AK49': 'ac2 load',
        'AK51': 'ac3 load',
        'J52': 'acComments',
        //Electric Section
        'K66': 'Main v1',
        'AC66': 'Main v2',
        'AZ66': 'Main v3',
        'K67': 'gen earth',
        'AC67': 'light earth',
        'AZ67': 'tel earth',
        'AZ68': 'leg earth',
        'K68': 'start dc',
        'AC68': 'end dc',
        'K69': 'fire',
        'AC69': 'owner load',
        'AZ69': 'neighbor load',
        'AC70': '3rd load',
        'K71': 'electricComments',
        'AL77': 'battery test',
        //Fuel Section
        'M87': 'T1 shape',
        'M88': 'T2 shape',
        'S87': 'T1',
        'S88': 'T2',
        'H90': 'engineer name'
      },
    },
    11: {
      'templateFileId': '1avxg7J3DGb9VLN1MuR_QYjlOk4SZQvaF2VJll71mNxU',
      'sheetName': '11',
      'cells': {
        //First Section
        'BE8': 'siteName',
        'AG8': 'date',
        'L9': 'location',
        'AG9': 'timeIn',
        'BE9': 'timeOut',
        'AG10': 'CP',
        'BE10': 'Kwh',
        'L12': 'Main v1',
        'AG12': 'Main v2',
        'BE12': 'Main v3',
        'L13': 'Main l1',
        'AG13': 'Main l2',
        'BE13': 'Main l3',
        'L14': 'HP',
        'AG14': 'LP',
        'BE14': 'room temp',
        'L15': 'generalComments',
        //G1,G2 Section
        'I20': 'G1',
        'N20': 'cycleForG1',
        'AB20': 'gen1 battery',
        'AF20': 'gen1 load 1',
        'AJ20': 'gen1 load 2',
        'AP20': 'gen1 load 3',
        'AS20': 'gen1 voltage ph-n1',
        'AX20': 'gen1 voltage ph-n2',
        'BA20': 'gen1 voltage ph-n3',
        'BC20': 'gen1 voltage ph-l1',
        'BG20': 'gen1 voltage ph-l2',
        'BI20': 'gen1 voltage ph-l3',
        'I21': 'g1Comments',
        //Replacement Section
        'Z24': 'g1 oil',
        'Z25': 'g1 oil',
        'Z26': 'g1 oil',
        'Z27': 'g1 gen sep',
        'Z28': 'g1 tank sep',
        'Z29': 'g1 air',
        'Z30': 'g1 coolant',
        'Z31': 'clean g1 air',
        //AC Section
        'J47': 'ac1 volt',
        'J49': 'ac2 volt',
        'J51': 'ac3 volt',
        'AK47': 'ac1 load',
        'AK49': 'ac2 load',
        'AK51': 'ac3 load',
        'J52': 'acComments',
        //Electric Section
        'K66': 'Main v1',
        'AC66': 'Main v2',
        'AZ66': 'Main v3',
        'K67': 'gen earth',
        'AC67': 'light earth',
        'AZ67': 'tel earth',
        'AZ68': 'leg earth',
        'K68': 'start dc',
        'AC68': 'end dc',
        'K69': 'fire',
        'AC69': 'owner load',
        'AZ69': 'neighbor load',
        'AC70': '3rd load',
        'K71': 'electricComments',
        'AL77': 'battery test',
        //Fuel Section
        'M87': 'T1 shape',
        'S87': 'T1',
        'H89': 'engineer name'
      },
    },
    12: {
      'templateFileId': '10YAqBVGOLQy1VQ6TtlfPGnesv6E1O0rMy1z6reIzVrI',
      'sheetName': '12',
      'cells': {
        //First Section
        'BB8': 'siteName',
        'AG8': 'date',
        'L9': 'location',
        'AG9': 'timeIn',
        'BB9': 'timeOut',
        'AG10': 'CP',
        'BB10': 'Kwh',
        'L12': 'Main v1',
        'AG12': 'Main v2',
        'BB12': 'Main v3',
        'L13': 'Main l1',
        'AG13': 'Main l2',
        'BB13': 'Main l3',
        'L14': 'HP',
        'AG14': 'LP',
        'BB14': 'room temp',
        'L15': 'generalComments',
        //G1,G2 Section
        'I20': 'G1',
        'N20': 'cycleForG1',
        'AB20': 'gen1 battery',
        'AF20': 'gen1 load 1',
        'AJ20': 'gen1 load 2',
        'AO20': 'gen1 load 3',
        'AQ20': 'gen1 voltage ph-n1',
        'AV20': 'gen1 voltage ph-n2',
        'AY20': 'gen1 voltage ph-n3',
        'AZ20': 'gen1 voltage ph-l1',
        'BD20': 'gen1 voltage ph-l2',
        'BF20': 'gen1 voltage ph-l3',
        'I21': 'g1Comments',
        //Replacement Section
        'Z27': 'g1 oil',
        'Z28': 'g1 oil',
        'Z29': 'g1 oil',
        'Z30': 'g1 gen sep',
        'Z31': 'g1 tank sep',
        'Z32': 'g1 air',
        'Z33': 'g1 coolant',
        'Z34': 'clean g1 air',
        //AC Section
        'J47': 'outdoor volt',
        'AK47': 'outdoor load',
        'J48': 'acComments',
        //Electric Section
        'K62': 'Main v1',
        'AC62': 'Main v2',
        'AX62': 'Main v3',
        'K63': 'gen earth',
        'AC63': 'light earth',
        'AX63': 'tel earth',
        'AX64': 'leg earth',
        'K64': 'start dc',
        'AC64': 'end dc',
        'K65': 'fire',
        'AC65': 'owner load',
        'AX65': 'neighbor load',
        'AC66': '3rd load',
        'K67': 'electricComments',
        'AL73': 'battery test',
        //Fuel Section
        'M83': 'T1 shape',
        'S83': 'T1',
        'H85': 'engineer name'
      },
    },
    13: {
      'templateFileId': '1L5muubk9d_JmIGCjPDkvBHoWFITUZtcEpqZcI0zKIf0',
      'sheetName': '13',
      'cells': {
        //First Section
        'BD8': 'siteName',
        'AG8': 'date',
        'L9': 'location',
        'AG9': 'timeIn',
        'BD9': 'timeOut',
        'AG10': 'CP',
        'BD10': 'Kwh',
        'L12': 'Main v1',
        'AG12': 'Main v2',
        'BD12': 'Main v3',
        'L13': 'Main l1',
        'AG13': 'Main l2',
        'BD13': 'Main l3',
        'L14': 'HP',
        'AG14': 'LP',
        'BD14': 'room temp',
        'L15': 'generalComments',
        //G1,G2 Section
        'I20': 'G1',
        'N20': 'cycleForG1',
        'AB20': 'gen1 battery',
        'AF20': 'gen1 load 1',
        'AJ20': 'gen1 load 2',
        'AQ20': 'gen1 load 3',
        'AS20': 'gen1 voltage ph-n1',
        'AX20': 'gen1 voltage ph-n2',
        'BA20': 'gen1 voltage ph-n3',
        'BB20': 'gen1 voltage ph-l1',
        'BF20': 'gen1 voltage ph-l2',
        'BH20': 'gen1 voltage ph-l3',
        'I21': 'g1Comments',
        //Replacement Section
        'Z24': 'g1 oil',
        'Z25': 'g1 oil',
        'Z26': 'g1 oil',
        'Z27': 'g1 gen sep',
        'Z28': 'g1 tank sep',
        'Z29': 'g1 air',
        'Z30': 'g1 coolant',
        'Z31': 'clean g1 air',
        //AC Section
        'J47': 'ac1 volt',
        'J49': 'ac2 volt',
        'AK47': 'ac1 load',
        'AK49': 'ac2 load',
        'J50': 'acComments',
        //Electric Section
        'K65': 'Main v1',
        'AC65': 'Main v2',
        'AZ65': 'Main v3',
        'K66': 'gen earth',
        'AC66': 'light earth',
        'AZ66': 'tel earth',
        'AZ67': 'leg earth',
        'K67': 'start dc',
        'AC67': 'end dc',
        'K68': 'fire',
        'AC68': 'owner load',
        'AZ68': 'neighbor load',
        'AC69': '3rd load',
        'K70': 'electricComments',
        'AL76': 'battery test',
        //Fuel Section
        'M86': 'T1 shape',
        'S86': 'T1',
        'H88': 'engineer name'
      },
    },
    14: {
      'templateFileId': '1-g0h60MX__HJ6uat_TXKpPzbZQh1mKHaCr8VLB96fiw',
      'sheetName': '14',
      'cells': {
        //First Section
        'BD8': 'siteName',
        'AG8': 'date',
        'L9': 'location',
        'AG9': 'timeIn',
        'BD9': 'timeOut',
        'AG10': 'CP',
        'BD10': 'Kwh',
        'L12': 'Main v1',
        'AG12': 'Main v2',
        'BD12': 'Main v3',
        'L13': 'Main l1',
        'AG13': 'Main l2',
        'BD13': 'Main l3',
        'L14': 'HP',
        'AG14': 'LP',
        'BD14': 'room temp',
        'L15': 'generalComments',
        //G1,G2 Section
        'I20': 'G1',
        'N20': 'cycleForG1',
        'AB20': 'gen1 battery',
        'AF20': 'gen1 load 1',
        'AJ20': 'gen1 load 2',
        'AQ20': 'gen1 load 3',
        'AS20': 'gen1 voltage ph-n1',
        'AX20': 'gen1 voltage ph-n2',
        'BA20': 'gen1 voltage ph-n3',
        'BB20': 'gen1 voltage ph-l1',
        'BF20': 'gen1 voltage ph-l2',
        'BH20': 'gen1 voltage ph-l3',
        'I21': 'g1Comments',
        //Replacement Section
        'Z24': 'g1 oil',
        'Z25': 'g1 oil',
        'Z26': 'g1 oil',
        'Z27': 'g1 gen sep',
        'Z28': 'g1 tank sep',
        'Z29': 'g1 air',
        'Z30': 'g1 coolant',
        'Z31': 'clean g1 air',
        //AC Section
        'J47': 'ac3 volt',
        'AK47': 'ac3 load',
        'J49': 'outdoor volt',
        'AK49': 'outdoor load',
        'J50': 'acComments',
        //Electric Section
        'K65': 'Main v1',
        'AC65': 'Main v2',
        'AZ65': 'Main v3',
        'K66': 'gen earth',
        'AC66': 'light earth',
        'AZ66': 'tel earth',
        'AZ67': 'leg earth',
        'K67': 'start dc',
        'AC67': 'end dc',
        'K68': 'fire',
        'AC68': 'owner load',
        'AZ68': 'neighbor load',
        'AC69': '3rd load',
        'K70': 'electricComments',
        'AL76': 'battery test',
        //Fuel Section
        'M86': 'T1 shape',
        'S86': 'T1',
        'H88': 'engineer name'
      },
    },
    15: {
      'templateFileId': '10yIiKIGehh0fxaIboWg_duFq3lTYReS5YguA-BVVbq8',
      'sheetName': '15',
      'cells': {
        //First Section
        'BB8': 'siteName',
        'AF8': 'date',
        'L9': 'location',
        'AF9': 'timeIn',
        'BB9': 'timeOut',
        'L12': 'Main v1',
        'L13': 'Main l1',
        'BB14': 'room temp',
        // 'L15': 'generalComments',

        //Electric Section
        'K31': 'Main v1',
        'AD32': 'light earth',
        'AW32': 'tel earth',
        'AW33': 'leg earth',
        'K33': 'start dc',
        'AD33': 'end dc',
        'K34': 'fire',
        'K36': 'electricComments',
        'AL42': 'battery test',
        'H53': 'engineer name'
      },
    },
    16: {
      'templateFileId': '1ezhK5Q4SID3hkyrSGjriba0Je6VZJOPwHXD5YLVECnM',
      'sheetName': '16',
      'cells': {
        //First Section
        'BG8': 'siteName',
        'AG8': 'date',
        'L9': 'location',
        'AG9': 'timeIn',
        'BG9': 'timeOut',
        'AG10': 'CP',
        'BG10': 'Kwh',
        'L12': 'Main v1',
        'AG12': 'Main v2',
        'BG12': 'Main v3',
        'L13': 'Main l1',
        'AG13': 'Main l2',
        'BG13': 'Main l3',
        'L14': 'HP',
        'AG14': 'LP',
        'BG14': 'room temp',
        'L15': 'generalComments',
        //G1,G2 Section
        'I20': 'G1',
        'N20': 'cycleForG1',
        'AB20': 'gen1 battery',
        'AF20': 'gen1 load 1',
        'AJ20': 'gen1 load 2',
        'AP20': 'gen1 load 3',
        'AS20': 'gen1 voltage ph-n1',
        'AY20': 'gen1 voltage ph-n2',
        'BD20': 'gen1 voltage ph-n3',
        'BE20': 'gen1 voltage ph-l1',
        'BI20': 'gen1 voltage ph-l2',
        'BL20': 'gen1 voltage ph-l3',
        'I21': 'g1Comments',
        'I22': 'G2',
        'N22': 'cycleForG2',
        'AB22': 'gen2 battery',
        'AF22': 'gen1 load 1',
        'AJ22': 'gen1 load 2',
        'AP22': 'gen1 load 3',
        'AS22': 'gen2 voltage ph-n1',
        'AY22': 'gen2 voltage ph-n2',
        'BD22': 'gen2 voltage ph-n3',
        'BE22': 'gen2 voltage ph-l1',
        'BI22': 'gen2 voltage ph-l2',
        'BL22': 'gen2 voltage ph-l3',
        'I23': 'g2Comments',
        //Replacement Section
        'Z27': 'g1 oil',
        'Z28': 'g1 oil',
        'Z29': 'g1 oil',
        'Z30': 'g1 gen sep',
        'Z31': 'g1 tank sep',
        'Z32': 'g1 air',
        'Z33': 'g1 coolant',
        'Z34': 'clean g1 air',
        'AN27': 'g2 oil',
        'AN28': 'g2 oil',
        'AN29': 'g2 oil',
        'AN30': 'g2 gen sep',
        'AN31': 'g2 tank sep',
        'AN32': 'g2 air',
        'AN33': 'g2 coolant',
        'AN34': 'clean g2 air',
        //AC Section
        'J50': 'ac1 volt',
        'J52': 'ac2 volt',
        'J54': 'ac3 volt',
        'J56': 'outdoor volt',
        'AK50': 'ac1 load',
        'AK52': 'ac2 load',
        'AK54': 'ac3 load',
        'AK56': 'outdoor load',
        'J57': 'acComments',
        //Electric Section
        'K71': 'Main v1',
        'AC71': 'Main v2',
        'BA71': 'Main v3',
        'K72': 'gen earth',
        'AC72': 'light earth',
        'BA72': 'tel earth',
        'BA73': 'leg earth',
        'K73': 'start dc',
        'AC73': 'end dc',
        'K74': 'fire',
        'AC74': 'owner load',
        'BA74': 'neighbor load',
        'AC75': '3rd load',
        'K76': 'electricComments',
        'AL82': 'battery test',
        //Fuel Section
        'M92': 'T1 shape',
        'M93': 'T2 shape',
        'M94': 'T3 shape',
        'S92': 'T1',
        'S93': 'T2',
        'S94': 'T3',
        'H97': 'engineer name'
      },
    },
  };

  Map<String, dynamic> getSheetMapping(int sheetNumber) {
    if (sheetMappings.containsKey(sheetNumber)) {
      return sheetMappings[sheetNumber]!['cells'] as Map<String, dynamic>;
    } else {
      throw Exception('Invalid sheet number');
    }
  }

  String getTemplateFileId(int sheetNumber) {
    if (sheetMappings.containsKey(sheetNumber)) {
      return sheetMappings[sheetNumber]!['templateFileId'] as String;
    } else {
      throw Exception('Invalid sheet number');
    }
  }

  String getSheetName(int sheetNumber) {
    if (sheetMappings.containsKey(sheetNumber)) {
      return sheetMappings[sheetNumber]!['sheetName'] as String;
    } else {
      throw Exception('Invalid sheet number');
    }
  }
}
